---
title: "2: Discipline"
subtitle: "Sociology, Science, and Their Core Concepts"
format:
  html:
    mainfont: "Source Serif Pro"
    monofont: "Source Sans Pro"
    grid:
      margin-width: 350px
  pdf: default
reference-location: margin
citation-location: margin
bibliography: ../nick.bib
csl: ../american-sociological-association.csl
---

# Introduction

Here is one (very negative) view about the current state of Sociology:

> According to Ray Rodrigues, chancellor of the state university system, Florida lawmakers began eyeing general education as a target of reform after complaints from parents. Their children would come home for Thanksgiving break during their first semester in college and would “be communicating cultural Marxism”...Under SB 266 \[a Florida state law intended to eliminate "woke" ideology\], courses that count toward general-education credit should “promote and preserve the constitutional republic” through “traditional, historically accurate” coursework. The law also says that “core courses” may not “distort significant historical events,” “include a curriculum that teaches identity politics,” or be based on theories that systemic racism, sexism, oppression, and privilege are inherent in American institutions.[^1]

[^1]: ["Is Sociology Being Saved — or Debased — in Florida?"](https://www-chronicle-com.proxy.library.stonybrook.edu/article/the-curricular-cull) *Chronicle of Higher Education*, March 16, 2026.

There is much to unpack in this statement. For now, we will leave aside the meaning of "cultural Marxism."[^2] We will also only briefly note that colleges explicitly advertise themselves as places to "push boundaries, challenge assumptions and redefine what's possible,"[^3] so one would *expect* young people to *want* to discuss new and interesting ideas with their family. We will also only glancingly note that "promot\[ing\] and preserv\[ing\] the constitutional republic" is *itself* an ideological goal, and that pursuing it explicitly could and would bias our understanding of society just like an explicitly "woke" one would.

[^2]: I seriously doubt that Rodrigues and his allies are reading Gramsci, Lukacs, or Benjamin, and instead, are simply using "cultural Marxism" as a catch-all for ideologies they don't like. See A.J.A. Woods, *The Cultural Marxism Conspiracy*, Verso, 2026.

[^3]: [Stony Brook's Webpage](https://www.stonybrook.edu/), accessed June 27th, 2026.

Instead, I want to take aim at what seems to be a foundational assumption of those criticizing sociology: that there is a way to pursue a completely unbiased, objective, neutral study of society. The authors of the Flordia state law imply, by claiming to cleanse University curriculum of "distortions," that there *is* an objective, true, and indisputable nature of society and history that is like the things we know about the physical history of the universe, biological dynamics, or the engineering of the material environment.

As you will see below, at a very basic level sociology (and the rest of the social sciences) do not work this way. This is because they take as their central object *people in society*, and since people *react* to their understandings about the world and the meaning they take from it, they need to be studied in a different way than rocks, planets, and pathogens.[^4] However, this does *not* mean that the social sciences and particularly sociology are therefore simply a realm where we assert opinions and call them facts; instead, it means that we have a wide inventory of careful, systematic ways of understanding the world, as well as many key concepts and theoretical traditions, and our job here in part is to introduce them.

[^4]: As noted in the previous unit, this is Du Bois' notion of **reflexivity**.

# What Is A Science?

To answer the question "what kind of science is sociology?", we need to answer a prior question: just what is a **science**? And to do *that* we have to take yet another step backwards, and, in turn, ask two basic questions about the structure of the world:

1. What kinds of things make up the world?
2. How do we know what those things are?

These are both ultimately philosophical questions.  The first is a question of **ontology**---sometimes also called "metaphysics"---and represents our best understanding of not only what the smallest, most basic parts of the world are, but also how those parts combine into all of the things that exist.  The second question, meanwhile, is one of **epistemology**; *if* the world is populated with certain things, how can we know what they are?

`More on ontological realism and epistemological instrumentation; why the answers to both of these questions are not simply a matter of naive empiricism.`

`Also, more on emergence.`

All sciences share ontological and epistemological commitments. Two of the most important are related to `no supernatural expalanation` and `no settling of theoretical or empirical disputes by appeals to only power or authority.`

Beyond those shared commitments, however, most sciences express very different ontological assumptions and use very different epistemological tools to learn about the world (these collections of tools, meanwhile, are what we call "methods"!)

`The relationship between sociology and the other social and physical sciences is largely one of the ontological assumptions each field makes, and of the epistemological tools---"methods"---that are most common in each.`

### STEM

`Usually assume atomism and a highly elaborated epistemological apparatus.  Example: quantum field theory.`

### Psychology

`Psychology's central tendency is to ontologically assume a self with a personality (generally)`

### Economics and Political Science

### Anthropology

# Components of a science

## What Is A Theory?

`A theory is a statement about how at least two different elements of the world relate to one another.`

`They can vary from descriptive to highly formal statements.`

## What Is A Hypothesis?

`Scientists generally think that theories are best when they are parsimonious (containing a few simple elements) and general (able to explain at least a whole class of cases). One way to extend and deepen theories is to ask what they *predict* about the world.  If that prediction comes to pass, we typically call the underlying theory *corroborated*, and when it does not, we typically call the prediction *falsified*.  Collectively, this process of making guesses based on our theoretical knowledge and then trying them out in the world is what we call **hypothetical** reasoning.`

## What Is Evidence?

`At base, any science is interested in a phenomenon of some kind (plural "phenomna"), which is the broad label for something taking place in the world. When we are interested in one or a few phenomena, we usually call them *particular*, and when we are interested in very broad phenomena, we call them *general*.`

`"Evidence" is the general name for the traces of phenomena we can observe, either directly with our senses or through various well-understood technological apparatuses.`

## What Is A Method?

`A "method" is just a name for how these bodies of theory and evidnce are put into dialog with one another.  Having sets of ways to establish this dialog allows use to form 'communities of inquiry,' which is to say, groups of scientists who share familiarity with a given method.`

## Some Tensions In A Pluralistic Science

How I have described science above is quite broad, and encompasses everything from a naturalist wading in a tidal pond to a theoretical physicist hypothesizing about the birth of the universe to an anthropologist observing a group's folkways. This is a highly *plural* view of science, which emphasizes its diveristy and resists efforts to reduce it to one or another "best" version---that is, instead of saying that laboratory experiments are indisputably the "most scientific" of any method, or that economics has a self-evidently better body of theory than political science, the theme of this perspective on science is that *any* method, kind of evidence, and theory should be considered as "science" so long as it does not appeal to supernatural explanations or pure authority and power to justify itself.

`The problem of value-commitments`

`The technical problem of commensuration`

`The substantive problem of scarcity---only so many resources in society, not enough to fund every method or science.  So what counts as "useful"?`

# Key Concepts and Theories in Contemporary Sociology

## Key Concepts

### Social Construction

One of the simplest and most direct, but also most notorious, concepts in sociology is social construction. If you have ever played any kind of game, engaged in make-believe with a young child, read fiction, or traveled in an unfamiliar culture, you have encountered social constructions and been aware of doing so. But *also*, if you ever used a bank, been in love, celebrated a birthday, or spoken to another person, you've also encountered a social construction, but perhaps with less awareness.

### Micro, Macro, Meso

`Sociologists generally admit that there are at least two ontological scales to social phenomena: the micro and macro levels.  There is substantial dispute about the existence of a third (meso) level.  This dispute revolves primarily around the generalizability of theories.`

### Agency and Structure

`This is an application of the classic question of "do we have free will"?`

### Social Order and Social Change

`The two classic, "big" statements of this are Durkheim's dissertation book and Tonnies.`

`Industrial capitalism and cultural modernity.`

## Key Theories in Contemporary Sociology

### Structural/Functionalism

`A macro-theory that emphasizes how any particular phenomenon does or does not contribute to the overall functioning/dysfunctioning of society.`

`Manifest and latent functions.`

### Symbolic Interactionism

`Approach that emphasizes micro-interactions and the shared basis of meaning that makes coordinated social life possible.`

### Conflict Theory/Marxism

`A key agonistic theory emphasizing how society is internally conflicted over the interests of different social groups.  Most famously over positions in the political economy of capitalism.`

### Practice Theory


### Feminist and Intersectional Theory

