---
title: "6: Structures and Organizations"
format:
  html:
    mainfont: "Source Serif Pro"
    monofont: "Source Sans Pro"
    grid:
      margin-width: 350px
  pdf: default
reference-location: margin
citation-location: margin
bibliography: ../nick.bib
csl: ../american-sociological-association.csl
---

# Introduction

So far, our journey through the foundational concepts in sociology has taken us through [meaning](/chatpers/Ch_4_Meaning.html)---the significance that the world holds for us---and [interaction](/chapters/Ch_5_Interaction.html)---how those meanings emerge from cues we see in the world around us and in other people. I have also emphasized the increasing complexity of society,[^1] which is to say, the now nearly-overwhelming set of meanings and interactions that are available to you, as a member of a Contemporary Industrial Society.

[^1]: In my discussion of [cultural development](/chatpers/Ch_4_Meaning.html) in human societies.

# Structures

The combination of the importance of meanings and interactions and their proliferation in complex societies begs the question: how are meanings and interactions *organized*? To put this more concretely, think of your commute to campus (or, if you live on campus, your walk to the lecture hall for class).[^2] As you take every step (if you're walking) or make every turn (if driving) or wait for your delayed LIRR train (if taking public transit), consider how *difficult* that step in your journey would be if you couldn't rely on other people's behavior being at least somewhat *predictable.*

[^2]: You can substitute nearly any task you need to accomplish in your daily life, if you prefer.

Now, I don't mean that you know every single thing that each individual person you meet is going to do. Instead, I mean that you can say to yourself, for instance

> I am on a train. I can expect that, if I keep my headphones in and focused on my phone, the only direct interaction I will have is when the conductor checks my ticket. Anything else is an unusual interaction.[^3]

[^3]: For those of you scoring at home, yes, this is an example of *civil inattention* from our discussion of [interaction](/chapters/Ch_5_Interaction.html)!

or

> I am driving to campus on Nicholls road. That means that many people around me will be driving far above the speed limit, but if I stay comfortably in the slow lane, I can listen to a podcast as I drive.

or

> I am leaving my dorm and have not yet eaten. However, since it's the middle of the semester on a Tuesday, I can plan to pick something up from the food trucks by the SAC or walk over to Druthers for a muffin.

The point here is that your experience would become unmanageable, and social life would grind to a halt, if you couldn't rely on these kinds of expectations in your daily life.[^4] But, overwhelmingly, you *can* count on these patterns of interaction and significance to exist, and sociologists refer to such patterns as **social structures**.

[^4]: More technically, this is a *functionalist* argument for the necessity of basic social organization.

::: column-margin
A **social structure** is a pattern of significance that endows interactions with (at least minimal) predictability.
:::

# Groups

`Activity to demonstrate small groups: get each person to say who they're sitting next to, and also who they know best in the class.  Make a network diagram to show the difference between an assembly and a group.`

- Primary group
- Secondary group
- Reference group

## The Power of Groups

`From small group analysis/Asch, demonstrate the kinds of coercion a group can exhibit.`

# Organizations

`Small groups and formal organizations.`

## The Power of Organizations

`Demonstrate the necessity and power of formal organizations in the modern world to categorize and control people.`

# Contemporary Dynamics

`The "network society".  Social capital analysis.`
